### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by linklel11**
Fixing typo's/Misspelling again. (sorry i make so many little pull requests)

### CODE REVIEW

**Comment by TheArmagan** [comment]
Can you write a better description for the app (For me) :D My English can't handle that :D

**Comment by linklel11** [comment]
Sure :)

**Comment by linklel11** [comment]
Do you wish me to Write more? or
is this Good for now?

**Comment by TheArmagan** [comment]
Yep they are very good thanks :)

**Pull request merged**
